version: "3.7"

services:
  nodered:
    image: nodered-img
    container_name: nodered-ctnr

    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        - TZ=America/Sao_Paulo
    
    ports:
      - target: 1880
        published: 1880
      - target: 9229
        published: 9229
        
    networks:
      - nodered-net

    volumes:
      - "./../data:/data"
      - "./../ozmap-sdk:/data/node_modules/ozmap-sdk"
      - ".:/data/node_modules/node-red-contrib-ozmap"

    environment:
      ACCESS_KEY: "----"
      SECRET_KEY: "----"
      BUCKET_BACKUP: "backups-node-red"
      FOLDER_BACKUP: "nrtestes/flows.json"

networks:
  nodered-net:
